# Generated by Django 5.2.17 on 2026-09-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='idempotency_key',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
