# Generated by Django 5.2.17 on 2026-09-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_alter_transaction_idempotency_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='request_fingerprint',
            field=models.CharField(db_index=True, default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
