# Generated by Django 5.2.17 on 2026-09-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_transaction_request_fingerprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='request_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
